import { IPost } from "../../models/IPost";

export const posts: IPost[] = [
  {
    id: '1',
    title: 'Example Post 1',
    user_id: '1',
    user_name: 'User 1',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is an example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.',
    creation_date: '2023-04-16',
  },
  {
    id: '2',
    title: 'Example Post 2',
    user_id: '2',
    user_name: 'User 2',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is another example post content.',
    creation_date: '2023-04-15',
  },{
    id: '1',
    title: 'Example Post 1',
    user_id: '1',
    user_name: 'User 1',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is an example post content.',
    creation_date: '2023-04-16',
  },
  {
    id: '2fdd589a-8964-4124-ab51-00b7f3686ab8',
    title: 'Example Post 2',
    user_id: '2fdd589a-8964-4124-ab51-00b7f3686ab8',
    user_name: 'User 2',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.',
    creation_date: '2023-04-15',
  },{
    id: '1',
    title: 'Example Post 1',
    user_id: '1',
    user_name: 'User 1',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is an example post content.',
    creation_date: '2023-04-16',
  },
  {
    id: '2fdd589a-8964-4124-ab51-00b7f3686ab8',
    title: 'Example Post 2',
    user_id: '2fdd589a-8964-4124-ab51-00b7f3686ab8',
    user_name: 'User 2',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content. ',
    creation_date: '2023-04-15',
  },
  {
    id: '1',
    title: 'Example Post 1',
    user_id: '1',
    user_name: 'User 1',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is an example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.',
    creation_date: '2023-04-16',
  },
  {
    id: '2',
    title: 'Example Post 2',
    user_id: '2',
    user_name: 'User 2',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is another example post content.',
    creation_date: '2023-04-15',
  },{
    id: '1',
    title: 'Example Post 1',
    user_id: '1',
    user_name: 'User 1',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is an example post content.',
    creation_date: '2023-04-16',
  },
  {
    id: '2fdd589a-8964-4124-ab51-00b7f3686ab8',
    title: 'Example Post 2',
    user_id: '2fdd589a-8964-4124-ab51-00b7f3686ab8',
    user_name: 'User 2',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.',
    creation_date: '2023-04-15',
  },{
    id: '1',
    title: 'Example Post 1',
    user_id: '1',
    user_name: 'User 1',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is an example post content.',
    creation_date: '2023-04-16',
  },
  {
    id: '2fdd589a-8964-4124-ab51-00b7f3686ab8',
    title: 'Example Post 2',
    user_id: '2fdd589a-8964-4124-ab51-00b7f3686ab8',
    user_name: 'User 2',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content. ',
    creation_date: '2023-04-15',
  },
  {
    id: '1',
    title: 'Example Post 1',
    user_id: '1',
    user_name: 'User 1',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is an example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.',
    creation_date: '2023-04-16',
  },
  {
    id: '2',
    title: 'Example Post 2',
    user_id: '2',
    user_name: 'User 2',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is another example post content.',
    creation_date: '2023-04-15',
  },{
    id: '1',
    title: 'Example Post 1',
    user_id: '1',
    user_name: 'User 1',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is an example post content.',
    creation_date: '2023-04-16',
  },
  {
    id: '2fdd589a-8964-4124-ab51-00b7f3686ab8',
    title: 'Example Post 2',
    user_id: '2fdd589a-8964-4124-ab51-00b7f3686ab8',
    user_name: 'User 2',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.',
    creation_date: '2023-04-15',
  },{
    id: '1',
    title: 'Example Post 1',
    user_id: '1',
    user_name: 'User 1',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is an example post content.',
    creation_date: '2023-04-16',
  },
  {
    id: '2fdd589a-8964-4124-ab51-00b7f3686ab8',
    title: 'Example Post 2',
    user_id: '2fdd589a-8964-4124-ab51-00b7f3686ab8',
    user_name: 'User 2',
    image: 'https://via.placeholder.com/300x140',
    content: 'This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content.This is another example post content. ',
    creation_date: '2023-04-15',
  },
];